// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: schema/market_side.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketSide int32

const (
	MarketSide_MARKET_SIDE_UNSPECIFIED MarketSide = 0
	MarketSide_ASK                     MarketSide = 1
	MarketSide_BID                     MarketSide = 2
)

// Enum value maps for MarketSide.
var (
	MarketSide_name = map[int32]string{
		0: "MARKET_SIDE_UNSPECIFIED",
		1: "ASK",
		2: "BID",
	}
	MarketSide_value = map[string]int32{
		"MARKET_SIDE_UNSPECIFIED": 0,
		"ASK":                     1,
		"BID":                     2,
	}
)

func (x MarketSide) Enum() *MarketSide {
	p := new(MarketSide)
	*p = x
	return p
}

func (x MarketSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketSide) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_market_side_proto_enumTypes[0].Descriptor()
}

func (MarketSide) Type() protoreflect.EnumType {
	return &file_schema_market_side_proto_enumTypes[0]
}

func (x MarketSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketSide.Descriptor instead.
func (MarketSide) EnumDescriptor() ([]byte, []int) {
	return file_schema_market_side_proto_rawDescGZIP(), []int{0}
}

var File_schema_market_side_proto protoreflect.FileDescriptor

var file_schema_market_side_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f,
	0x73, 0x69, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x68, 0x61, 0x72,
	0x74, 0x73, 0x2a, 0x3b, 0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x53, 0x69, 0x64, 0x65,
	0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x53, 0x49, 0x44, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x53, 0x4b, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x49, 0x44, 0x10, 0x02, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f,
	0x65, 0x79, 0x63, 0x75, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x2d, 0x73, 0x77, 0x79, 0x66, 0x74, 0x78,
	0x2f, 0x63, 0x68, 0x61, 0x72, 0x74, 0x73, 0x2d, 0x75, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_schema_market_side_proto_rawDescOnce sync.Once
	file_schema_market_side_proto_rawDescData = file_schema_market_side_proto_rawDesc
)

func file_schema_market_side_proto_rawDescGZIP() []byte {
	file_schema_market_side_proto_rawDescOnce.Do(func() {
		file_schema_market_side_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_market_side_proto_rawDescData)
	})
	return file_schema_market_side_proto_rawDescData
}

var file_schema_market_side_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_market_side_proto_goTypes = []interface{}{
	(MarketSide)(0), // 0: charts.MarketSide
}
var file_schema_market_side_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_market_side_proto_init() }
func file_schema_market_side_proto_init() {
	if File_schema_market_side_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_market_side_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_market_side_proto_goTypes,
		DependencyIndexes: file_schema_market_side_proto_depIdxs,
		EnumInfos:         file_schema_market_side_proto_enumTypes,
	}.Build()
	File_schema_market_side_proto = out.File
	file_schema_market_side_proto_rawDesc = nil
	file_schema_market_side_proto_goTypes = nil
	file_schema_market_side_proto_depIdxs = nil
}
